version: '3.8'

services:
  frontend:
    image: token_scraper_frontend:latest
    container_name: frontend
    ports:
      - "6789:6789"
    volumes:
      - logs:/app/logs


  backend:
    image: token_scraper_backend:latest
    container_name: backend
    depends_on:
      - frontend
    environment:
      - SOCKET_ADDRESS=frontend
    ports:
      - "6789:6789"

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/token-scraper/token-scraper-logs
